/**
 * Sends an AI agent link action email (booking or purchase) to the specified user.
 *
 * @augments WlSdk_ModelAbstract
 * @constructor
 */
function Wl_AiAgent_Link_SendMailModel()
{
  WlSdk_ModelAbstract.apply(this);

  /**
   * Purchase item ID. Required if {@link Wl_AiAgent_Link_SendMailModel.text_action} is 'purchase'.
   *
   * One of the {@link RsPurchaseItemSid} constants.
   *
   * @post get
   * @see RsPurchaseItemSid
   * @type {number}
   */
  this.id_purchase_item = 0;

  /**
   * Service ID. Required if {@link Wl_AiAgent_Link_SendMailModel.text_action} is 'booking'.
   *
   * @post get
   * @see RsServiceSid
   * @type {number}
   */
  this.id_service = 0;

  /**
   * Business key. Required.
   *
   * @post get
   * @type {string}
   */
  this.k_business = "";

  /**
   * Unique identifier for the link.
   *
   * @post get
   * @type {string}
   */
  this.k_id = "";

  /**
   * Action type. Must be 'purchase' or 'booking'.
   *
   * @post get
   * @type {string}
   */
  this.text_action = "";

  /**
   * URL suffix for the link. Optional.
   *
   * @post get
   * @type {string}
   */
  this.text_url_suffix = "";

  /**
   * User ID. Required.
   *
   * @post get
   * @type {string}
   */
  this.uid = "";

  this.changeInit();
}

WlSdk_ModelAbstract.extend(Wl_AiAgent_Link_SendMailModel);

/**
 * @inheritDoc
 */
Wl_AiAgent_Link_SendMailModel.prototype.config=function()
{
  return {"a_field":{"id_purchase_item":{"post":{"get":true}},"id_service":{"post":{"get":true}},"k_business":{"post":{"get":true}},"k_id":{"post":{"get":true}},"text_action":{"post":{"get":true}},"text_url_suffix":{"post":{"get":true}},"uid":{"post":{"get":true}}}};
};

/**
 * Sends an AI agent link action email (booking or purchase) to the specified user.
 *
 * Triggers the email that the AI agent sends when a client clicks a booking or purchase link
 * generated by the AI agent chat. Requires the business to have an active AI agent subscription;
 * the action type determines which notification template is used and which service or purchase
 * item is referenced in the email body.
 *
 * @function
 * @name Wl_AiAgent_Link_SendMailModel.post
 * @returns {WlSdk_Deferred_Promise}
 * @see WlSdk_ModelAbstract.post()
 */
