/**
 * Sends the "Phone Agent Call Received" staff notification to every active staff member of the business who
 * has the {@link Wl_Privilege_PrivilegeSid} permission.
 *
 * @augments WlSdk_ModelAbstract
 * @constructor
 */
function Wl_AiAgent_Phone_CallReceivedModel()
{
  WlSdk_ModelAbstract.apply(this);

  /**
   * How the call ended. Required.
   *
   * @post get
   * @type {number}
   */
  this.id_call_outcome = 0;

  /**
   * Business key. Required.
   *
   * @post get
   * @type {string}
   */
  this.k_business = "";

  /**
   * Short summary of the call generated by CAASI. Used in the email notification only. Optional.
   *
   * @post get
   * @type {string}
   */
  this.text_call_summary = "";

  /**
   * The caller's name, if identified. Optional.
   *
   * @post get
   * @type {string}
   */
  this.text_caller_name = "";

  /**
   * The caller's phone number. Optional.
   *
   * @post get
   * @type {string}
   */
  this.text_caller_phone = "";

  /**
   * URL to view the conversation between the caller and CAASI (for email). Optional.
   *
   * @post get
   * @type {string}
   */
  this.url_view_conversation_link = "";

  /**
   * URL to view the conversation, in an SMS-safe format. Optional.
   *
   * @post get
   * @type {string}
   */
  this.url_view_conversation_link_sms = "";

  this.changeInit();
}

WlSdk_ModelAbstract.extend(Wl_AiAgent_Phone_CallReceivedModel);

/**
 * @inheritDoc
 */
Wl_AiAgent_Phone_CallReceivedModel.prototype.config=function()
{
  return {"a_field":{"id_call_outcome":{"post":{"get":true}},"k_business":{"post":{"get":true}},"text_call_summary":{"post":{"get":true}},"text_caller_name":{"post":{"get":true}},"text_caller_phone":{"post":{"get":true}},"url_view_conversation_link":{"post":{"get":true}},"url_view_conversation_link_sms":{"post":{"get":true}}}};
};

/**
 * Sends the "Phone Agent Call Received" staff notification to every active staff member of the business who
has the {@link Wl_Privilege_PrivilegeSid} permission.
 *
 * Requires the business to have an active Phone Agent subscription tier.
 *
 * @function
 * @name Wl_AiAgent_Phone_CallReceivedModel.post
 * @returns {WlSdk_Deferred_Promise}
 * @see WlSdk_ModelAbstract.post()
 */
