name: Sonar

on:
  workflow_dispatch:
  push:
    branches:
      - stable
#  pull_request:
#    types: [opened, synchronize, reopened]

jobs:
  sonar:
    name: Sonar scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v5.3.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
